// This file will be generated by Better Auth CLI.
// Currently acts as a placeholder to prevent import errors.
export const user = {};
export const session = {};
export const account = {};
export const verification = {};
